import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest
from sqlalchemy.orm import Session
from app.db.database import SessionLocal
from app.models.models import Item, PriceHistory, AnalysisResult
import logging

logger = logging.getLogger(__name__)

class AnomalyDetector:
    def __init__(self, contamination=0.05):
        self.model = IsolationForest(contamination=contamination, random_state=42)

    def analyze_item(self, item_id: int, db: Session) -> bool:
        """
        Runs advanced ML anomaly detection using financial indicators (Rolling Windows, Z-Scores).
        """
        # 1. Fetch history, but limit to last 30 days to keep the model focused on current reality
        # 30 days * 24 hours = 720 records max
        history = db.query(PriceHistory).filter(PriceHistory.item_id == item_id)\
            .order_by(PriceHistory.timestamp.desc()).limit(720).all()
        
        # Reverse to chronological order
        history.reverse()
        
        # Need at least 24 hours of data to calculate meaningful moving averages
        if len(history) < 24:
            return False

        data = [{
            "timestamp": h.timestamp,
            "lowest_price": h.lowest_price,
            "volume": h.volume
        } for h in history]
        
        df = pd.DataFrame(data)

        # ==========================================
        # ADVANCED FEATURE ENGINEERING (QUANT STYLE)
        # ==========================================
        
        # 1. Basic Momentum
        df['price_change'] = df['lowest_price'].pct_change().fillna(0)
        df['volume_change'] = df['volume'].pct_change().fillna(0)

        # 2. Simple Moving Average (SMA) - 24 hours
        df['SMA_24h'] = df['lowest_price'].rolling(window=24, min_periods=1).mean()
        
        # 3. Z-Score for Price (How far is current price from the 24h average in standard deviations)
        # Formula: Z = (X - Mu) / Sigma
        df['price_std_24h'] = df['lowest_price'].rolling(window=24, min_periods=1).std().fillna(0.001) # avoid div by zero
        df['price_z_score'] = (df['lowest_price'] - df['SMA_24h']) / df['price_std_24h']

        # 4. Z-Score for Volume (Detects sudden accumulation or dump)
        df['vol_SMA_24h'] = df['volume'].rolling(window=24, min_periods=1).mean()
        df['vol_std_24h'] = df['volume'].rolling(window=24, min_periods=1).std().fillna(0.001)
        df['volume_z_score'] = (df['volume'] - df['vol_SMA_24h']) / df['vol_std_24h']

        # Drop NaN values generated by rolling functions
        df = df.fillna(0)

        # ==========================================
        # ISOLATION FOREST TRAINING
        # ==========================================
        
        # The model now looks at Z-scores (contextual bounds) rather than just raw prices
        features = df[['price_change', 'volume_change', 'price_z_score', 'volume_z_score']]

        df['anomaly'] = self.model.fit_predict(features)
        
        scores = self.model.decision_function(features)
        df['risk_score'] = ValidateRiskScore(scores)

        # Extract latest data point for current evaluation
        latest_data = df.iloc[-1]
        
        # Hybrid Trigger: It's an anomaly if ML says so, OR if the Z-Score is extremely high (>3.0)
        # 3.0 Z-score means there is a 99.7% chance this movement is unnatural.
        ml_anomaly = bool(latest_data['anomaly'] == -1)
        statistical_anomaly = abs(latest_data['price_z_score']) > 3.0 or abs(latest_data['volume_z_score']) > 4.0
        
        is_anomaly = ml_anomaly or statistical_anomaly
        current_risk_score = float(latest_data['risk_score'])

        # Save to DB
        self._save_results(db, item_id, is_anomaly, current_risk_score)
        
        return True

    def _save_results(self, db: Session, item_id: int, is_anomaly: bool, risk_score: float):
        existing_result = db.query(AnalysisResult).filter(AnalysisResult.item_id == item_id).first()
        if existing_result:
            existing_result.is_anomaly = is_anomaly
            existing_result.risk_score = risk_score
            existing_result.created_at = pd.Timestamp.utcnow()
        else:
            new_result = AnalysisResult(
                item_id=item_id,
                is_anomaly=is_anomaly,
                risk_score=risk_score
            )
            db.add(new_result)
        db.commit()

def ValidateRiskScore(scores_array) -> np.ndarray:
    min_score = scores_array.min()
    max_score = scores_array.max()
    if max_score == min_score:
        return np.zeros_like(scores_array)
    normalized = (scores_array - min_score) / (max_score - min_score)
    risk_scores = (1 - normalized) * 100
    return np.round(risk_scores, 2)