"""update_price_history_columns

Revision ID: 7074f149b0d7
Revises: 91ffb0fb0ae3
Create Date: 2026-03-20 20:57:25.311657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7074f149b0d7'
down_revision: Union[str, Sequence[str], None] = '91ffb0fb0ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('lowest_price', sa.Float(), nullable=True))
    op.add_column('price_history', sa.Column('median_price', sa.Float(), nullable=True))
    op.drop_column('price_history', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('price_history', 'median_price')
    op.drop_column('price_history', 'lowest_price')
    # ### end Alembic commands ###
